### ISSUE TITLE
无法加载schem格式（schem格式错误?）

### ISSUE THREAD

**Issue by Chiloven945** [DevBobcorn/MarkovCraft#4]
WorldEdit：
```log
[17:28:08 ERROR]: Uncaught exception occurred in task: Loading schematic ctf.schem
java.util.NoSuchElementException: No tag under the name 'Schematic' exists
        at org.enginehub.linbus.tree.LinCompoundTag.getTag(LinCompoundTag.java:380) ~[worldedit-bukkit-7.3.0-beta-02.jar:?]
        at com.sk89q.worldedit.extent.clipboard.io.sponge.SpongeSchematicV3Reader.getBaseTag(SpongeSchematicV3Reader.java:92) ~[worldedit-bu
kkit-7.3.0-beta-02.jar:?]
        at com.sk89q.worldedit.extent.clipboard.io.sponge.SpongeSchematicV3Reader.read(SpongeSchematicV3Reader.java:61) ~[worldedit-bukkit-7
.3.0-beta-02.jar:?]
        at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:356) ~[worldedit-bukkit-7.3.0-beta-02
.jar:?]
        at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:338) ~[worldedit-bukkit-7.3.0-beta-02
.jar:?]
        at com.sk89q.worldedit.command.util.AsyncCommandBuilder.runTask(AsyncCommandBuilder.java:158) ~[worldedit-bukkit-7.3.0-beta-02.jar:?
]
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFu
tureTask.java:131) ~[guava-31.1-jre.jar:?]
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74) ~[guava-31.1-jre.jar:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82) ~[guava-31.1-jre.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
FastAsyncWorldEdit：
```log
[17:15:22 WARN]: Failed to load a saved clipboard
java.io.IOException: This schematic version is not supported; Version: -1, DataVersion: -1. It's very likely your schematic has an invalid file extension, if the schematic has been created on a version lower than 1.13.2, the extension MUST be `.schematic`, elsewise the schematic can't be read properly.
```

**Comment by DevBobcorn** [comment]
你用的这个WorldEdit命令好像只支持旧版本的schematic（后缀是.schematic），新版的schematic格式不太一样，后缀是.schem

**Comment by DevBobcorn** [comment]
可能是WorldEdit版本有点旧了？

**Comment by DevBobcorn** [comment]
如果你还留着那个结构文件的话可以给我发一下吗，我看一下里面的内容
